immigration_forum/urls.py
from django.urls import path, include
from immigration_forum.views import HomeView, CountryView, AddPostView, BlogView, EditPostView, ShowPostView, \
    DeletePostView, AddCommentView, like_post_view

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('country/<int:pk>/', CountryView.as_view(), name='country_details'),
    path('add_post/', AddPostView.as_view(), name='add_post'),
    path('blog/', BlogView.as_view(), name='blog'),
    path('post/<int:pk>/edit_post/', EditPostView.as_view(), name='edit_post'),
    path('post/<int:pk>/', ShowPostView.as_view(), name='show_post'),
    path('post/<int:pk>/delete_post/', DeletePostView.as_view(), name='delete_post'),
    path('post/<int:pk>/add_comment/', AddCommentView.as_view(), name='add_comment'),
    path('post/<int:pk>/like/', like_post_view, name='like_post'),
]

immigration_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include('immigration_forum.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
    path('api/', include('immigration_api.urls')),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.urls import path, include
from members.views import UserRegisterView, UserEditView, PasswordChangeView, password_success, choose_profile, \
    CreateUserProfileView, CreateConsultantProfileView, ShowUserProfileView, ShowConsultantProfileView, \
    UpdateUserProfileView, UpdateConsultantProfileView

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('edit_settings/', UserEditView.as_view(), name='edit_settings'),
    path('password/', PasswordChangeView.as_view()),
    path('password/success/', password_success, name='password_success'),
    path('choose_profile/', choose_profile, name='choose_profile'),
    path('create_user_profile/', CreateUserProfileView.as_view(), name='create_user_profile'),
    path('create_consultant_profile/', CreateConsultantProfileView.as_view(), name='create_consultant_profile'),
    path('user_profile/<int:pk>/', ShowUserProfileView.as_view(), name='show_user_profile'),
    path('consultant_profile/<int:pk>/', ShowConsultantProfileView.as_view(), name='show_consultant_profile'),
    path('update_user_profile/<int:pk>/', UpdateUserProfileView.as_view(), name='update_user_profile'),
    path('update_consultant_profile/<int:pk>/', UpdateConsultantProfileView.as_view(), name='update_consultant_profile'),
]

immigration_forum/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField


class Country(models.Model):
    name = models.CharField(max_length=50)
    info = models.TextField()
    snippet = models.CharField(max_length=255)
    flag = models.ImageField(blank=True, null=True, upload_to='images/country/')

    class Meta:
        verbose_name_plural = 'Countries'

    def __str__(self):
        return self.name


class UserProfile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE, related_name='userprofile')
    bio = models.TextField(max_length=1000)
    profile_pic = models.ImageField(blank=True, null=True, upload_to='images/user_profile/')
    website_url = models.CharField(max_length=255, blank=True, null=True)
    instagram_url = models.CharField(max_length=255, blank=True, null=True)
    facebook_url = models.CharField(max_length=255, blank=True, null=True)
    twitter_url = models.CharField(max_length=255, blank=True, null=True)
    linkedin_url = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'


class ConsultantProfile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE, related_name='consultantprofile')
    country = models.ForeignKey(Country, on_delete=models.PROTECT)
    bio = models.TextField(max_length=1200)
    profile_pic = models.ImageField(blank=True, null=True, upload_to='images/consultant_profile/')
    website_url = models.CharField(max_length=255, blank=True, null=True)
    instagram_url = models.CharField(max_length=255, blank=True, null=True)
    facebook_url = models.CharField(max_length=255, blank=True, null=True)
    twitter_url = models.CharField(max_length=255, blank=True, null=True)
    linkedin_url = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'


class Post(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(ConsultantProfile, on_delete=models.CASCADE)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, default=1)
    body = RichTextField(blank=True, null=True)
    date_posted = models.DateField(auto_now_add=True)
    header_image = models.ImageField(blank=True, null=True, upload_to='images/')
    likes = models.ManyToManyField(User, related_name='posts', null=True)

    def __str__(self):
        return f'{self.title} - by {self.author}'

    def total_likes(self):
        return self.likes.count()


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField(max_length=1000)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment to "{self.post}" - by {self.author}'

immigration_forum/forms.py
from django import forms
from immigration_forum.models import Post, Country, Comment


class AddPostForm(forms.ModelForm):
    title = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}), required=True)
    body = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    country = forms.ModelChoiceField(queryset=Country.objects.all(),
                                     widget=forms.Select(attrs={'class': 'form-control'}))
    header_image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}), required=False)

    class Meta:
        model = Post
        fields = ['title', 'body', 'country', 'header_image']


class EditPostForm(forms.ModelForm):
    title = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}), required=True)
    body = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    country = forms.ModelChoiceField(queryset=Country.objects.all(),
                                     widget=forms.Select(attrs={'class': 'form-control'}))
    header_image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}), required=False)

    class Meta:
        model = Post
        fields = ['title', 'body', 'country', 'header_image']


class AddCommentForm(forms.ModelForm):
    body = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))

    class Meta:
        model = Comment
        fields = ['body']

immigration_forum/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from .forms import AddPostForm, EditPostForm, AddCommentForm
from .models import Country, Post, Comment


class HomeView(ListView):
    model = Country
    template_name = 'home.html'


class CountryView(DetailView):
    model = Country
    template_name = 'country_details.html'

    def get_context_data(self, **kwargs):
        context = super(CountryView, self).get_context_data(**kwargs)
        context['post_list'] = Post.objects.filter(country=self.kwargs['pk'])
        return context


class BlogView(ListView):
    model = Post
    template_name = 'blog.html'


class AddPostView(CreateView):
    model = Post
    form_class = AddPostForm
    template_name = 'add_post.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.instance.author = self.request.user.consultantprofile
        return super().form_valid(form)


class EditPostView(UpdateView):
    model = Post
    form_class = EditPostForm
    template_name = 'edit_post.html'


class ShowPostView(DetailView):
    model = Post
    template_name = 'show_post.html'

    def get_context_data(self, *args, **kwargs):
        context = super(ShowPostView, self).get_context_data(*args, **kwargs)
        post = get_object_or_404(Post, id=self.kwargs['pk'])
        is_liked = False

        if post.likes.filter(id=self.request.user.id).exists():
            is_liked = True

        total_likes = post.total_likes()
        context['total_likes'] = total_likes
        context['is_liked'] = is_liked
        return context


class DeletePostView(DeleteView):
    model = Post
    template_name = 'delete_post.html'
    success_url = reverse_lazy('home')


class AddCommentView(CreateView):
    model = Comment
    template_name = 'add_comment.html'
    form_class = AddCommentForm
    # success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.instance.post_id = self.kwargs['pk']
        form.instance.author_id = self.request.user.id
        return super().form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse('show_post', kwargs={'pk': self.object.post_id})


def like_post_view(request, pk):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    is_liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        is_liked = False
    else:
        post.likes.add(request.user)
        is_liked = True
    return HttpResponseRedirect(reverse('show_post', args=[str(pk)]))

immigration_forum/templates/add_comment.html
{% extends 'base.html' %}

{% block title %}
    Add Comment
{% endblock %}

{% block content %}
    <br/>
    <h3>Add New Comment</h3>
    <br/>
    <div class="mb-3">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-info">Add Comment</button>
    </div>
{% endblock %}

immigration_forum/templates/add_post.html
{% extends 'base.html' %}}

{% block title %}
    Add New Post
{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        {% if user.consultantprofile.id %}
            <br/><br/>
            <h3>Add New Post</h3>
            <br/>
            <div class="mb-3">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.media }}
                {{ form.as_p }}
                <button class="btn btn-info">Post</button>
            </div>
        {% elif user.userprofile.id %}
            <br/><br/>
            <strong>You need to be a consultant to make a new post. Please enjoy our blog!</strong>
        {% else %}
            <br/><br/>
            <strong>You need to create a Consultant profile to make a new post</strong>
            <br/><br/>
            <a href="{% url 'create_profile_page' %}">Create Profile</a>
            <br/><br/>
        {% endif %}
    {% else %}
        <strong>You need to Log In to add a new post!</strong>
        <br/><br/>
        <a href="{% url 'login' %}">Log in</a>
        <br/><br/>
        <a href="{% url 'register' %}">Register</a>
        <br/><br/>
        <a href="{% url 'home' %}" class="btn btn-info">Back</a>
    {% endif %}
{% endblock %}

immigration_forum/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
    {% block title %}
        Immigrate Now!
    {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>

  <body>
  {% load static %}
    <nav class="navbar sticky-top navbar-expand-lg" style="background-color: #e3f2fd;">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static 'immigration_forum/images/logo.png' %}" width="50" height="24">
        Immigrate Now!
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Countries</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog' %}">Blog</a>
            </li>
            {% if user.is_authenticated %}
              {% if user.consultantprofile.id %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'add_post' %}">Add Post</a>
            </li>
              {% endif %}
            {% endif %}

          </ul>



          <ul class="navbar-nav ms-auto">

            {% if user.is_authenticated %}
              {% if user.userprofile.id %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    {{user.first_name}} {{user.last_name}}
                  </a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'show_user_profile' user.userprofile.id %}">See Profile Page</a></li>
                    <li><a class="dropdown-item" href="{% url 'update_user_profile' user.userprofile.id %}">Edit Profile Page</a></li>
                    <li><a class="dropdown-item" href="{% url 'edit_settings'%}">Edit Settings</a></li>
                  </ul>
                </li>
              {% elif user.consultantprofile.id %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    {{user.first_name}} {{user.last_name}}
                  </a>
                  <ul class="dropdown-menu">
                    <li>
                      <a class="dropdown-item" href="{% url 'show_consultant_profile' user.consultantprofile.id %}">
                      See Profile Page
                      </a>
                    </li>
                    <li>
                      <a class="dropdown-item" href="{% url 'update_consultant_profile' user.consultantprofile.id %}">
                        Edit Profile Page
                      </a>
                    </li>
                    <li><a class="dropdown-item" href="{% url 'edit_settings'%}">Edit Settings</a></li>
                  </ul>
                </li>
              {% else %}
                <li class="nav-item">
                <a class="nav-link" href="{% url 'choose_profile' %}">Create Profile Page</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'edit_settings' %}">Edit Settings</a>
                </li>
            <li class="nav-item">
              {% endif %}
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>

            {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>

            {% endif %}
        </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

immigration_forum/templates/blog.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Blog
{% endblock %}

{% block content %}

<table class="table table-light table-bordered table align-middle">
  <tbody>
  {% for post in post_list %}
    <tr>
      <th style="width: 15.00%">
          <div class="shadow p-4 mb-1 bg-body rounded" style="text-align:center">
          <h5><a href="{% url 'show_consultant_profile' post.author.id %}" class="link-dark">
                <img src="{{ post.author.profile_pic.url }}" width="110" height="120"><br/>
                {{ post.author }}
            </a></h5>
          </div>
      </th>
        <td>
            <a href="{% url 'country_details' post.country.id %}">
                <img src="{{ post.country.flag.url }}" width="35" height="20">
            <a/>
            <br/><br/>
            <h4>{{ post.title }}</h4> <a href="{% url 'show_post' post.pk %}">Read post...</a>
            {% if user.is_authenticated %}
                {% if user.consultantprofile.id %}
                    {% if user.consultantprofile.id == post.author.id %}
                        <small>
                            <a href="{% url 'edit_post' post.id %}" class="link-secondary">(Edit)</a>
                            <a href="{% url 'delete_post' post.pk %}" class="link-danger">(Delete)</a>
                        </small>
                    {% endif %}
                {% endif %}
            {% endif %}
        </td>
    </tr>
  </tbody>
    {% endfor %}
</table>

{% endblock %}

immigration_forum/templates/country_details.html
{% extends 'base.html' %}

{% block title %}
    {{ country }}
{% endblock %}

{% block content %}
    <br/><br/>
    <img src="{{ country.flag.url }}" width="200" height="120"><br/><br/>
    <h2> {{ country }}</h2>

    <br/><br/>
    {{ country.info }}
    <br/><br/><br/><br/>
    {% if post_list %}
    <h3>Blog about {{ country }}</h3>
    <br/>
    <table class="table table-light table-bordered table align-middle">
        <tbody>
            {% for post in post_list %}
            <tr>
              <th style="width: 15.00%">
                  <div class="shadow p-4 mb-1 bg-body rounded" style="text-align:center">
                  <h5><a href="{% url 'show_consultant_profile' post.author.id %}" class="link-dark">
                        <img src="{{ post.author.profile_pic.url }}" width="110" height="120"><br/>
                        {{ post.author }}
                    </a></h5>
                  </div>
              </th>
                <td>
                     <a href="{% url 'country_details' post.country.id %}">
                        <img src="{{ post.country.flag.url }}" width="35" height="20">
                     <a/>
                    <br/><br/>
                    <h4>{{ post.title }}</h4> <a href="{% url 'show_post' post.pk %}">Read post...</a>
                    {% if user.is_authenticated %}
                        {% if user.consultantprofile.id %}
                            {% if user.consultantprofile.id == post.author.id %}
                                <small>
                                    <a href="{% url 'edit_post' post.id %}" class="link-secondary">(Edit)</a>
                                    <a href="{% url 'delete_post' post.pk %}" class="link-danger">(Delete)</a>
                                </small>
                            {% endif %}
                        {% endif %}
                    {% endif %}
                </td>
            </tr>
        </tbody>
            {% endfor %}
    </table>
    {% endif %}
{% endblock %}

immigration_forum/templates/delete_post.html
{% extends 'base.html' %}

{% block title %}
    Delete Post
{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        {% if user.consultantprofile.id %}
            {% if user.consultantprofile.id == post.author.id %}
                <br/>
                <h3>Delete Post</h3>
                <br/>
                <div class="mb-3">
                <form method='POST'>
                    {% csrf_token %}
                    <strong>Are you sure you want to delete "{{ post.title }}"?</strong>
                    <br/><br/><br/>
                    <button class="btn btn-danger">Delete</button>
                </div>
            {% else %}
                <br/>
                <strong>You are not allowed to delete this post!</strong>
                <br/>
                <br/>
                <a href="{% url 'home' %}" class="btn btn-info">Back</a>
            {% endif %}
        {% else %}
            <br/>
            <strong>You are not allowed to delete this post!</strong>
            <br/>
            <br/>
            <a href="{% url 'home' %}" class="btn btn-info">Back</a>
        {% endif %}
    {% else %}
        <br/>
        <strong>You are not allowed to delete this post!</strong>
        <br/>
        <br/>
        <a href="{% url 'home' %}" class="btn btn-info">Back</a>
    {% endif %}

{% endblock %}

immigration_forum/templates/edit_post.html
{% extends 'base.html' %}

{% block title %}
    Edit Post
{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        {% if user.consultantprofile.id  %}
            {% if user.consultantprofile.id == post.author.id %}
                <br/>
                    <h3>Edit Post</h3>
                <br/>
                <div class="mb-3">
                <form method='POST'>
                    {% csrf_token %}
                    {{ form.media }}
                    {{ form.as_p }}
                    <button class="btn btn-info">Update</button>
                </div>
            {% else %}
                <br/>
                <strong>You are not allowed to edit this post!</strong>
                <br/>
                <br/>
                <a href="{% url 'blog' %}" class="btn btn-info">Back</a>
            {% endif %}
        {% else %}
                <br/>
                <strong>Only consultants can edit posts</strong>
                <br/>
                <br/>
                <a href="{% url 'blog' %}" class="btn btn-info">Back</a>
        {% endif %}
    {% else %}
        <strong>You need to Log In to edit this post!</strong>
        <br/><br/>
        <a href="{% url 'login' %}">Log in</a>
        <br/><br/>
        <a href="{% url 'register' %}">Register</a>
        <br/><br/>
        <a href="{% url 'home' %}" class="btn btn-info">Back</a>
    {% endif %}

{% endblock %}

immigration_forum/templates/home.html
{% extends 'base.html' %}}
{% load static %}}
{% block content %}
<br/><br/>
<!--<ul>-->
<!--    {% for country in country_list %}-->
<!--    <li>-->
<!--        <h5><a href="{% url 'country_details' country.pk %}" class="link-dark">-->
<!--           {{ country }}-->
<!--       </a></h5>-->
<!--        <img src="{% static 'immigration_forum/images/1.png' %}" width="30" height="18">-->
<!--    <br/>-->
<!--    </li>-->
<!--    {% endfor %}-->
<!--</ul>-->


<table class="table table-light table-bordered table align-middle">
  <tbody>
  {% for country in country_list %}
    <tr>
      <th style="width: 15.00%">
          <div class="shadow p-4 mb-1 bg-body rounded" style="text-align:center">
          <h5><a href="{% url 'country_details' country.pk %}" class="link-dark">
          <img src="{{ country.flag.url }}" width="110" height="60"><br/>
           {{ country }}
            </a></h5>
          </div>
      </th>
        <td>
            {{ country.snippet }}
        </td>

    </tr>
  </tbody>
    {% endfor %}
</table>




{% endblock %}

immigration_forum/templates/show_post.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ post }}
{% endblock %}

{% block content %}
    <br/>
    <h3>{{ post.title }}</h3>
    <small>
        by
        <a href="{% url 'show_consultant_profile' post.author.id %}" class="link-secondary">{{ post.author }}</a>
        about
        <a href="{% url 'country_details' post.country.id %}" class="link-secondary">
            {{ post.country }}
            <img src="{{ post.country.flag.url }}" witgh="20" height="14">
        </a>
         - {{ post.date_posted }}
        {% if user.is_authenticated %}
            {% if user.consultantprofile.id %}
                {% if user.consultantprofile.id == post.author.id %}
                    <small>
                        <a href="{% url 'edit_post' post.id %}" class="link-secondary">(Edit)</a>
                        <a href="{% url 'delete_post' post.pk %}" class="link-danger">(Delete)</a>
                    </small>
                {% endif %}
            {% endif %}
        {% endif %}
        <br/>
    </small>
    <br/>
    {% if post.header_image %}
        <img src="{{ post.header_image.url }}">
    {% endif %}
    <br/>
    {{ post.body|safe }}
    <br/>
    <hr/>
    <br/>

    {% if user.is_authenticated %}
        <form action="{% url 'like_post' post.pk %}" method="POST">
            {% csrf_token %}
            {% if is_liked %}
                <button type="submit" name="post_id" value="{{ post.id }}" class="btn btn-outline-danger btn-sm">
                    Unlike
                </button>
            {% else %}
                <button type="submit" name="post_id" value="{{ post.id }}" class="btn btn-outline-info btn-sm">
                    Like
                </button>
            {% endif %}
    {% else %}
        <small><i><a href="{% url 'login' %}">Log in to like</a></i></small>
    {% endif %}
        - {{ total_likes }} like(s)
    </form>
    <hr/>

    <h5>Comment section</h5>
    {% if not post.comments.all %}
        No comments yet
        <br/>
        <a href="{% url 'add_comment' post.pk %}">Add a comment</a>
    {% else %}
        <a href="{% url 'add_comment' post.pk %}">Add a comment</a>
        <br/><br/>
        {% for comment in post.comments.all %}
            <div class="shadow p-3 mb-5 bg-body rounded">
                <strong>{{ comment.author }} - {{ comment.date_added }}</strong>
                <br/><br/>
                {{ comment.body }}
            </div>
        {% endfor %}
    {% endif %}

{% endblock %}